# Generated by Django 2.2.6 on 2019-10-21 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pioneering', '0005_auto_20191019_1845'),
        ('reports', '0002_monthlyfieldservice_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyfieldservice',
            name='pioneering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mfs', to='pioneering.PioneerDetail'),
        ),
    ]
