# Generated by Django 2.2.6 on 2019-11-19 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_monthlyfieldservice_pioneering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyfieldservice',
            options={'ordering': ('publisher__last_name', 'publisher__first_name', 'publisher__middle_name')},
        ),
    ]
