# Generated by Django 2.2.6 on 2019-11-19 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20191119_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyfieldservice',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher_mfs', to='publishers.Publisher'),
        ),
    ]
