# Generated by Django 2.2.6 on 2019-11-06 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=200)),
                ('ssl', models.BooleanField(default=True)),
                ('tls', models.BooleanField(default=True)),
                ('ssl_port', models.SmallIntegerField()),
                ('tls_port', models.SmallIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('email_address', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='mail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('sent', models.BooleanField(blank=True, default=False)),
                ('user_mail', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='mailing.UserMail')),
            ],
        ),
    ]
