# Generated by Django 2.2.6 on 2019-11-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermail',
            name='ssl',
        ),
        migrations.RemoveField(
            model_name='usermail',
            name='ssl_port',
        ),
        migrations.AlterField(
            model_name='usermail',
            name='tls_port',
            field=models.SmallIntegerField(default=587),
        ),
    ]
