# Generated by Django 2.2.6 on 2019-10-09 17:25

from django.db import migrations, models
import django.db.models.deletion
import pioneering.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publishers', '0005_auto_20191009_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='PioneerDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pioneer_type', models.CharField(choices=[(pioneering.models.PioneerType('Auxillary Pioneer'), 'Auxillary Pioneer'), (pioneering.models.PioneerType('Regular Pioneer'), 'Regular Pioneer'), (pioneering.models.PioneerType('Special Pioneer'), 'Special Pioneer')], max_length=2)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pioneer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publishers.Publisher')),
            ],
        ),
    ]
