# Generated by Django 2.2.6 on 2019-10-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioneering', '0002_pioneerdetail_pioneer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pioneerdetail',
            name='pioneer_type',
            field=models.CharField(choices=[('AU', 'Auxillary Pioneer'), ('RP', 'Regular Pioneer'), ('SP', 'Special Pioneer')], max_length=2),
        ),
    ]
