# Generated by Django 2.2.6 on 2019-10-19 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pioneering', '0003_auto_20191015_2021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pioneer',
            options={'ordering': ('publisher__last_name', 'publisher__first_name', 'publisher__middle_name')},
        ),
        migrations.AddField(
            model_name='pioneerdetail',
            name='has_ended',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='pioneer',
            name='code',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pioneer',
            name='is_active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='pioneer',
            name='publisher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pioneering', to='publishers.Publisher'),
        ),
    ]
