# Generated by Django 2.2.6 on 2019-10-19 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pioneering', '0004_auto_20191019_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pioneerdetail',
            name='pioneer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='pioneering.Pioneer'),
        ),
    ]
