# Generated by Django 2.2.6 on 2019-11-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioneering', '0005_auto_20191019_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pioneer',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='pioneerdetail',
            name='has_ended',
            field=models.BooleanField(blank=True, default=False, editable=False),
        ),
    ]
