# Generated by Django 2.2.6 on 2019-10-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_congregation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congregation',
            name='code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
