# Generated by Django 2.2.6 on 2019-11-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20191009_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gmail_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='gmail_password',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
