# Generated by Django 2.2.6 on 2019-11-20 15:14
from django.db import migrations


def make_initial_data_for_auth_group(apps, schema_editor):
    """ Make initial data for auth.Group

    Master Users
    Group Leaders
    Group Assistants
    Publishers
    """
    Group = apps.get_model('auth', 'Group')

    data = [
        {
            'id': 1,
            'name': 'Master Users',
        },  # master users
        {
            'id': 2,
            'name': 'Group Leaders',
        },  # group leaders
        {
            'id': 3,
            'name': 'Group Assistants',
        },  # group assistants
        {
            'id': 4,
            'name': 'Publishers',
        },
    ]
    for d in data:
        if not Group.objects.filter(pk=d['id']).exists():
            Group.objects.create(id=d['id'], name=d['name'])


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('system', '0005_auto_20191110_1652'),
    ]

    operations = [
        migrations.RunPython(make_initial_data_for_auth_group)
    ]
