# Generated by Django 2.2.6 on 2019-11-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_auto_20191120_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_data_runned', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
