# Generated by Django 2.2.6 on 2019-12-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='import_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
