# Generated by Django 2.2.6 on 2019-12-06 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_state_import_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('state__name', 'name')},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ('country__name', 'name')},
        ),
    ]
