# Generated by Django 2.2.6 on 2019-10-11 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publishers', '0005_auto_20191009_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyFieldService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_ending', models.DateField()),
                ('placements', models.PositiveSmallIntegerField(default=0)),
                ('video_showing', models.PositiveSmallIntegerField(default=0)),
                ('hours', models.PositiveSmallIntegerField(default=0)),
                ('return_visits', models.PositiveSmallIntegerField(default=0)),
                ('bible_study', models.PositiveSmallIntegerField(default=0)),
                ('comments', models.CharField(blank=True, max_length=255)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publishers.Publisher')),
            ],
        ),
    ]
