# Generated by Django 2.2.6 on 2019-10-15 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0006_auto_20191015_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_members', to='publishers.Publisher'),
        ),
    ]
