# Generated by Django 2.2.6 on 2019-10-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0007_auto_20191015_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
