# Generated by Django 2.2.6 on 2019-10-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0008_publisher_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ('last_name', 'first_name', 'middle_name')},
        ),
        migrations.AlterField(
            model_name='publisher',
            name='slug',
            field=models.SlugField(),
        ),
    ]
