# Generated by Django 2.2.6 on 2019-11-11 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publishers', '0009_auto_20191019_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publisher', to=settings.AUTH_USER_MODEL),
        ),
    ]
