# Generated by Django 2.2.6 on 2019-11-11 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0010_publisher_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ('-date_from', '-date_to')},
        ),
    ]
