# Generated by Django 2.2.6 on 2019-11-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0015_auto_20191119_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='assets',
            field=models.ManyToManyField(blank=True, related_name='publishers', to='publishers.Asset'),
        ),
    ]
