# Generated by Django 2.2.6 on 2019-11-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0016_auto_20191119_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpublisher',
            name='male',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='male',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
