# Generated by Django 2.2.6 on 2019-12-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0018_auto_20191125_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpublisher',
            name='male',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='male',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
