# Generated by Django 2.2.6 on 2019-12-05 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
        ('publishers', '0019_auto_20191205_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpublisher',
            name='address_line_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalpublisher',
            name='city',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cities.City'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='address_line_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.City'),
        ),
    ]
