# Generated by Django 2.2.6 on 2019-12-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0020_auto_20191205_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpublisher',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='publisher',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
