# Generated by Django 2.2.6 on 2019-11-19 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publishers', '0014_auto_20191119_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('elder', models.BooleanField(blank=True, default=False)),
                ('ms', models.BooleanField(blank=True, default=False, verbose_name='Ministerial Servant')),
                ('publisher', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='servant', to='publishers.Publisher')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalServant',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('elder', models.BooleanField(blank=True, default=False)),
                ('ms', models.BooleanField(blank=True, default=False, verbose_name='Ministerial Servant')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('publisher', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='publishers.Publisher')),
            ],
            options={
                'verbose_name': 'historical servant',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
