# Generated by Django 2.2.6 on 2019-11-19 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servant',
            options={'ordering': ('-elder', '-ms', 'publisher__last_name', 'publisher__first_name')},
        ),
    ]
