# Generated by Django 2.2.6 on 2019-10-09 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20191009_1651'),
        ('publishers', '0002_auto_20191009_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Congregation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('congregation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Congregation')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publishers.Publisher')),
            ],
        ),
    ]
