# Generated by Django 2.2.6 on 2019-10-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0003_congregation'),
    ]

    operations = [
        migrations.AddField(
            model_name='congregation',
            name='date_from',
            field=models.DateField(blank=True, null=True, verbose_name='from'),
        ),
        migrations.AddField(
            model_name='congregation',
            name='date_to',
            field=models.DateField(blank=True, null=True, verbose_name='to'),
        ),
        migrations.AddField(
            model_name='congregation',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
