# Generated by Django 2.2.6 on 2019-10-09 17:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20191009_1651'),
        ('publishers', '0004_auto_20191009_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('congregation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Congregation')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='from')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='to')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publishers.Group')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publishers.Publisher')),
            ],
        ),
        migrations.DeleteModel(
            name='Congregation',
        ),
    ]
