# Generated by Django 2.2.6 on 2019-10-09 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pioneering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pioneerdetail',
            name='pioneer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pioneering.Pioneer'),
            preserve_default=False,
        ),
    ]
